version: '3.9'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-proxy-fileserver
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
    - 3307:3306
    volumes:
    - mysql-proxy-fileserver:/var/lib/mysql

volumes:
  mysql-proxy-fileserver:

