name: Buid And Test
on:
  push:
    branches-ignore:
      - develop
      - main
  pull_request:
    branches-ignore:
      - develop
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build -o proxyserver ./cmd/main.go
      - name: Test
        run: go test ./...
      - name: Vet
        run: go vet ./...

