name: Deploy Dev

on:
  push:

env:
  KEY_BUILD_FILE: build_result

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: go build -o proxy-server ./cmd/main.go

      - name: Test
        run: go test ./...

      - name: Vet
        run: go vet ./...


  deploy:
    needs:
      - build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Combine Environments
        env:
          DEV_ENV_FILE: ${{ secrets.ENV_DEV}}
        run: echo $DEV_ENV_FILE | base64 --decode > .env

      - name: SSH to server
        run: echo "SSH to dev here ...."
      - name: SCP
        run: echo "SCP here ..."